### ISSUE TITLE
CB firewall icmp issue

### ISSUE THREAD

**Issue by maystery** [micado-scale/ansible-micado#66]
### Prerequisites

* [X] Can you reproduce the problem?
* [X] Did you perform a cursory search to see if your bug or enhancement is already reported?

### Description

After you deploy an application on CB-AWS platform the Occopus does not create the worker infrastructure.  

### Steps to Reproduce

1. Create MiCADO master on CB-AWS
2. Deploy an application

**Expected behavior:** Occopus should deploy the worker infrastructure

**Actual behavior:** After 600 s the infrastructure tear down by occopus

### Versions

MiCADO 0.5.0

### Additional context
Occopus log:
```
....
** 2018-08-08 10:45:24,910      DEBUG   MainProcess     Process exit code: 1
** 2018-08-08 10:45:24,910      INFO    MainProcess         ec2-18-212-138-140.compute-1.amazonaws.com => pending
** 2018-08-08 10:45:24,912      INFO    MainProcess     Health checking result: pending
** 2018-08-08 10:45:24,915      WARNING MainProcess     Service on node 'worker'/'e73ccbb2-f56b-45f4-a0e8-92dab25988d1' is down for 611.129 seconds! (Timeout for restart: 600s)
** 2018-08-08 10:45:24,916      ERROR   MainProcess     Strategy.perform: exception: Node has failed (state=failed)
** 2018-08-08 10:45:24,919      ERROR   MainProcess     A critical error (NodeFailedError) has occured, aborting remaining commands in this batch (infra_id: 'micado_worker_infra').
** 2018-08-08 10:45:24,920      DEBUG   MainProcess     Undoing create node for 'e73ccbb2-f56b-45f4-a0e8-92dab25988d1'
** 2018-08-08 10:45:24,920      INFO    MainProcess     Dropping node 'worker'/'e73ccbb2-f56b-45f4-a0e8-92dab25988d1'
** 2018-08-08 10:45:24,941      DEBUG   MainProcess     [https://cola-prototype.cloudbroker.com] Dropping node 'e73ccbb2-f56b-45f4-a0e8-92dab25988d1'
** 2018-08-08 10:45:25,536      DEBUG   MainProcess     [https://cola-prototype.cloudbroker.com] Done
** 2018-08-08 10:45:25,556      ERROR   MainProcess     Error occured, tearing down the infrastructure
** 2018-08-08 10:45:25,557      INFO    MainProcess     Start dropping infrastructure micado_worker_infra
** 2018-08-08 10:45:25,559      DEBUG   MainProcess     Dropping nodes: []
** 2018-08-08 10:45:25,560      DEBUG   MainProcess     Pushing instruction list: []
** 2018-08-08 10:45:25,560      DEBUG   MainProcess     Peforming instructions SEQUENTIALLY: []
** 2018-08-08 10:45:25,562      DEBUG   MainProcess     Pushing instruction list: (<occo.plugins.infraprocessor.basic_infraprocessor.DropInfrastructure object at 0x7f0354380790>,)
** 2018-08-08 10:45:25,563      DEBUG   MainProcess     Peforming instructions SEQUENTIALLY: (<occo.plugins.infraprocessor.basic_infraprocessor.DropInfrastructure object at 0x7f0354380790>,)
** 2018-08-08 10:45:25,563      DEBUG   MainProcess     Dropping infrastructure 'micado_worker_infra'
** 2018-08-08 10:45:25,563      DEBUG   MainProcess     [CM] Destroying environments for infrastructure 'micado_worker_infra'
** 2018-08-08 10:45:25,581      INFO    MainProcess     Finished dropping infrastructure micado_worker_infra
** 2018-08-08 10:45:25,582      ERROR   MainProcess     An unrecoverable error occured; the partially built infrastructure has been torn down, because of the following error:
** 2018-08-08 10:45:25,584      DEBUG   MainProcess     Traceback (most recent call last):
  File "/occopus.src/api/bin/occopus-build", line 85, in <module>
    enactor.make_a_pass()
  File "/occopus.src/enactor/occo/enactor/__init__.py", line 351, in make_a_pass
    self.enact_delta(delta)
  File "/occopus.src/enactor/occo/enactor/__init__.py", line 331, in enact_delta
    self.ip.push_instructions(self.infra_id, instruction_list)
  File "/occopus.src/infra-processor/occo/infraprocessor/__init__.py", line 80, in push_instructions
    rv = self.strategy.perform(self, instruction_list)
  File "/occopus.src/infra-processor/occo/infraprocessor/strategy.py", line 72, in perform
    return self._perform(infraprocessor, instruction_list)
  File "/occopus.src/infra-processor/occo/infraprocessor/strategy.py", line 147, in _perform
    result = i.perform(infraprocessor)
  File "/occopus.src/infra-processor/occo/plugins/infraprocessor/basic_infraprocessor.py", line 124, in perform
    self._perform_create(infraprocessor, instance_data)
  File "/occopus.src/infra-processor/occo/plugins/infraprocessor/basic_infraprocessor.py", line 207, in _perform_create
    resolved_node_def['create_timeout'])
  File "/occopus.src/infra-processor/occo/infraprocessor/synchronization/__init__.py", line 136, in wait_for_node
    raise NodeFailedError(instance_data, status)
NodeFailedError: Node has failed (state=failed)```

** 2018-08-08 10:45:25,584      ERROR   MainProcess     Node has failed (state=failed)

**Comment by maystery** [comment]
I have turned off the Occopus ping health check on CloudBroker platform. The firewall of the platform is not capable of filtering ICMP. https://github.com/micado-scale/component_submitter/commit/506d8b5d0ab74d269281c1111b144a11733b3276
